(source (official cli))
(config username "Paul Tsnobiladzé")
(config project_name stork)
(config npm_username dialohq)
(config github_username dialohq)
(config project_description "A JSON migrator CLI for ATD")
(config package_manager Esy)
(config ci_cd Github)
(config syntax OCaml)
(config project_snake stork)
(config project_slug stork)
(config test_framework Rely)
